apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-resource-sync
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      platzService: resource-sync
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        platzService: resource-sync
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.resourceSync.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: resource-sync
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{- .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}'
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command:
            - /root/platz-resource-sync
          env:
            {{ include "database.envVars" $ | nindent 12 }}
            - name: PLATZ_OWN_URL
              value: '{{ include "platz.ownUrl" . }}'
            - name: RUST_BACKTRACE
              value: '1'
            - name: RUST_LOG
              value: 'debug,hyper=error,rustls=error,tower=error'
          resources:
            {{- toYaml .Values.resourceSync.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
